In [1]:
import pandas as pd
import numpy as np

path = './data/salud/'
base_axis = ['CONCEPTO', '1985', '1986', '1987',	'1988',	'1989',	'1990',	'1991',	'1992',	'1993',	'1994',	'1995',	'1996',	'1997',	'1998',	'1999',	'2000',	'2001',
             '2002',	'2003',	'2004',	'2005',	'2006',	'2007',	'2008',	'2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020']

# Cargar el fichero y formatear los espacios en blanco coincidentes en la mayoria de los ficheros
def load(file):
    return pd.read_excel(path + file)[6:]

**19.1 Personal facultativo del Ministerio de Salud Pública, en 31 de diciembre**

In [10]:
df = load('19.1 Personal facultativo del Ministerio de Salud Pública, en 31 de diciembre .xls')
a_axis='PERSONAL	1985	1986	1987	1988	1989	1990	1991	1992	1993	1994	1995	1996	1997	1998	1999	2000	2001	2002	2003	2004	2005	2006	2007	2008	2009	2010	2011	2012	2013	2014	2015	2016	2017 2018 2019	2020'.split()
df=df.replace('…',np.nan)
df=pd.concat([df.iloc[:,0:30],df.iloc[:,37:44]],axis=1).set_axis(a_axis,axis=1)

display(df.head())

,PERSONAL,1985,1986,1987,1988,1989,1990,1991,1992,1993,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
6,Total,71595.0,80121.0,88242.0,96586.0,106393.0,115428.0,122303.0,129717.0,132905.0,...,189707.0,191110.0,190655.0,196350.0,198450.0,199184.0,201456.0,203134.0,204160,214720
7,Médicos,22910.0,25567.0,28060.0,31229.0,34752.0,38690.0,42634.0,46860.0,51045.0,...,78622.0,82065.0,83698.0,85563.0,87982.0,90161.0,92084.0,95487.0,97202,103 835
8,De ello: Médicos de familia,761.0,2473.0,4021.0,6211.0,8965.0,11915.0,15141.0,18503.0,22021.0,...,13367.0,13419.0,13382.0,12842.0,12883.0,12883.0,13131.0,13070.0,26173,21 589
9,Estomatólogos,5335.0,5752.0,5923.0,6134.0,6482.0,6959.0,7515.0,8057.0,8531.0,...,12793.0,13998.0,15249.0,16630.0,17542.0,16852.0,18675.0,18910.0,19825,20 589
10,Farmacéuticos,610.0,650.0,664.0,634.0,649.0,719.0,766.0,857.0,543.0,...,1868.0,2916.0,3344.0,3392.0,2927.0,3099.0,3060.0,3005.0,2913,5 319

**19.2 Personal facultativo del Ministerio de Salud Pública por provincias**

In [98]:
df=pd.read_excel(path + '19.2 Personal facultativo del Ministerio de Salud Pública por provincias.xls').iloc[8:25]
b_axis='CONCEPTO Total Médicos	De_ellos_medico_de_familia Estomatólogos Farmacéuticos Enfermeras_auxiliares Tecnicos_auxiliares'.split()
c_axis='CONCEPTO Médicos	De_ellos_de_familia Estomatólogos Enfermeras'.split()
a2006=df.iloc[:-1,:8].set_axis(b_axis,axis=1)
a2007=df.iloc[:-1,8:16].set_axis(b_axis,axis=1)
a2008=df.iloc[:-1,16:24].set_axis(b_axis,axis=1)
a2009=df.iloc[:-1,25:33].set_axis(b_axis,axis=1)
a2010=df.iloc[:-1,33:38].set_axis(b_axis[:5],axis=1)
a2011=df.iloc[:,37:42].set_axis(c_axis,axis=1)
a2012=df.iloc[:,42:47].set_axis(c_axis,axis=1)
a2013=df.iloc[:,47:52].set_axis(c_axis,axis=1)
a2014=df.iloc[:,53:58].set_axis(c_axis,axis=1)
a2015=df.iloc[:,59:64].set_axis(c_axis,axis=1)
a2016=df.iloc[:,65:70].set_axis(c_axis,axis=1)
a2017=df.iloc[:,[71,72,74,75,77]].set_axis(c_axis,axis=1)
a2018=df.iloc[:,[79,80,81,83,85]].set_axis(c_axis,axis=1)
a2019=df.iloc[:,[87,88,90,91,93]].set_axis(c_axis,axis=1)
a2020=df.iloc[:,[95,96,98,100,101]].set_axis(c_axis,axis=1)

display(a2020)

,CONCEPTO,Médicos,De_ellos_de_familia,Estomatólogos,Enfermeras
8,Cuba,103 835,21589,20589.0,84977
9,Pinar del Río,5 138,838,873.0,4972
10,Artemisa,2 716,1083,551.0,3459
11,La Habana,22 827,3617,4123.0,14853
12,Mayabeque,1 997,632,560.0,2562
13,Matanzas,4 638,649,1102.0,4783
14,Villa Clara,7 766,1429,1612.0,6317
15,Cienfuegos,3 292,473,702.0,3111
16,Sancti Spíritus,4 521,692,756.0,3661
17,Ciego de Ávila,3 289,892,698.0,3029
18,Camagüey,6 346,1288,1503.0,5477
19,Las Tunas,4 601,1140,949.0,4333
20,Holguín,9 170,1649,1512.0,7237
21,Granma,8 343,2451,1828.0,8010
22,Santiago de Cuba,12 751,2785,2368.0,7793
23,Guantánamo,5 944,1885,1241.0,4543
24,Isla de la Juventud,496,86,211.0,837

**19.3  Habitantes por médico y estomatólogo**

In [107]:
d_axis='AÑOS	Total	habitantes_x_médico		Total	 habitantes_x_estomatólogo'.split()
df=pd.read_excel(path + '19.3  Habitantes por médico y estomatólogo.xls').iloc[11:,[0,1,2,4,5]].set_axis(d_axis,axis=1)
display(df.head())

    AÑOS  Total habitantes_x_médico Total habitantes_x_estomatólogo
11  1958   6286                1076   250                     27052
12  1965   6238                1252  1200                      6508
13  1970   6152                1389  1366                      6256
14  1975   9328                 996  2319                      4007
15  1980  15247                 641  3646                      2682